# Based on Felix Rieseberg
# https://github.com/felixrieseberg/travis-jekyll-git
# Or …?
# https://github.com/nielsenramon/kickster/tree/master/snippets/travis

language: ruby

rvm:
- 2.2.3

install:
- ./bin/setup

script:
- bundle exec jekyll build --trace
- bundle exec htmlproofer ./_site --only-4xx

#after_success:
#- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && "./bin/automated"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - USERNAME: dcanetma
  - EMAIL: dcanetma@gmail.com

# branch whitelist
#branches:
#  only:
#  - gh-pages     # test the gh-pages branch
#  - /pages-(.*)/ # test every branch which starts with "pages-"

# @todo
# notifications to flowdock?
# notification by email to christina?
