# Based on Felix Rieseberg
# https://github.com/felixrieseberg/travis-jekyll-git

language: ruby

rvm:
- 2.2.3

install:
- ./bin/setup

script:
- bundle exec jekyll build --trace
- bundle exec htmlproofer ./_site --only-4xx

# branch whitelist
branches:
  only:
  - gh-pages     # test the gh-pages branch
  - /pages-(.*)/ # test every branch which starts with "pages-"

#after_success:
#- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && "./bin/automated"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES: true
  
deploy:
  skip_cleanup: true
  provider: script
  script: bin/deploy.sh
  on:
    branch: gh-pages