language: ruby
rvm:
- 2.2.3

install:
- "./bin/setup"

script:
- bundle exec jekyll build --trace
- bundle exec htmlproofer ./_site --only-4xx

#after_success:
#- "./bin/deploy"

deploy:
 skip_cleanup: true
 provider: script
 script: bin/deploy
 on:
   branch: deploy

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - USERNAME: dcanetma
  - EMAIL: dcanetma@gmail.com
  - secure: cvU5Jv79qtkwtpqjJPAxEH2Onnjg4ZE+wOuhOor0cTf0jRRepEji7eCesBuaRtY7SGe7BeSmZyIdpJ3jTDkbYUhv/6xTik+7k++ix+yknmKTd3isxzgELfq1s6xOI4/jWxsq3sB49q8VdGJzVNSH6kp++AVxtbvfUYMUJ5vTfFluur6RgNVyDlOZDRz17VdnZio4UCTDYTMVhG83oej38fCzOZAz56+zEek4jCWtnt7cySmUrG+IolO0Pgd+SJQ8v+ls7udGrq6uls+7CK3aC5jB8mEVf6NLjwVFvghKzblhgp1idIHY6kIyUaPbJlBTYAWx7NoGn3qTDreXJx7nq7Ws6YWZSgnCeHuO5zv1fVXsrrmSoMJvg1hurrGolv2Iz5mPhMBvxgkLGuZorObcXURrT2xBKsvfUT37D7pkCWgkMC4bYOQ9yjUHfDv+gx+LyoJKu2x8MfljOiCuTmQd8v6SCHJtrzx9vPYIR0husgfg1xTh79GlnhYEGSUjJzwzKIaT+1teknl0dUGS3yetaJurxvHDJbguHNaxwiLpcfxrtpe6UBZwzykByygr6iXsf6zW2jdd/sUR9R/VJSqCG8ZduAGf3lsTW2GMH/0CoDJjvNAZ9I6XQVeZtVN9PRLd80WoTKODCFNNmvvIMJtN6Oea51rgk8g7AH6RjW45ACs=

notifications:
  flowdock: a3ab675b8495f55b53e6c3c6cf565d1e

#  email:
#    - true@factsandfictions.net
#    - schultzen101@yahoo.de